<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HourlyRateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('hourly_rates')->insert([
            // Alvin Antunes
            ['employeeId' => 1, 'zoneId' => 1, 'rate' => 29.32, 'start' => now(), 'end' => now()],
            ['employeeId' => 1, 'zoneId' => 2, 'rate' => 29.49, 'start' => now(), 'end' => now()],
            ['employeeId' => 1, 'zoneId' => 3, 'rate' => 29.78, 'start' => now(), 'end' => now()],
            ['employeeId' => 1, 'zoneId' => 4, 'rate' => 29.95, 'start' => now(), 'end' => now()],
            ['employeeId' => 1, 'zoneId' => 5, 'rate' => 30.18, 'start' => now(), 'end' => now()],
            ['employeeId' => 1, 'zoneId' => 6, 'rate' => 30.59, 'start' => now(), 'end' => now()],
            ['employeeId' => 1, 'zoneId' => 7, 'rate' => 30.94, 'start' => now(), 'end' => now()],
            // Mounir Ayeb
            ['employeeId' => 2, 'zoneId' => 1, 'rate' => 32.75, 'start' => now(), 'end' => now()],
            ['employeeId' => 2, 'zoneId' => 2, 'rate' => 32.92, 'start' => now(), 'end' => now()],
            ['employeeId' => 2, 'zoneId' => 3, 'rate' => 33.21, 'start' => now(), 'end' => now()],
            ['employeeId' => 2, 'zoneId' => 4, 'rate' => 33.38, 'start' => now(), 'end' => now()],
            ['employeeId' => 2, 'zoneId' => 5, 'rate' => 33.61, 'start' => now(), 'end' => now()],
            ['employeeId' => 2, 'zoneId' => 6, 'rate' => 34.02, 'start' => now(), 'end' => now()],
            ['employeeId' => 2, 'zoneId' => 7, 'rate' => 34.37, 'start' => now(), 'end' => now()],
            // Alcindo Barreto
            ['employeeId' => 3, 'zoneId' => 1, 'rate' => 43.59, 'start' => now(), 'end' => now()],
            ['employeeId' => 3, 'zoneId' => 2, 'rate' => 43.76, 'start' => now(), 'end' => now()],
            ['employeeId' => 3, 'zoneId' => 3, 'rate' => 44.05, 'start' => now(), 'end' => now()],
            ['employeeId' => 3, 'zoneId' => 4, 'rate' => 44.22, 'start' => now(), 'end' => now()],
            ['employeeId' => 3, 'zoneId' => 5, 'rate' => 44.45, 'start' => now(), 'end' => now()],
            ['employeeId' => 3, 'zoneId' => 6, 'rate' => 44.86, 'start' => now(), 'end' => now()],
            ['employeeId' => 3, 'zoneId' => 7, 'rate' => 45.21, 'start' => now(), 'end' => now()],
            // Rui Beito Amorin
            ['employeeId' => 4, 'zoneId' => 1, 'rate' => 29.26, 'start' => now(), 'end' => now()],
            ['employeeId' => 4, 'zoneId' => 2, 'rate' => 29.43, 'start' => now(), 'end' => now()],
            ['employeeId' => 4, 'zoneId' => 3, 'rate' => 29.72, 'start' => now(), 'end' => now()],
            ['employeeId' => 4, 'zoneId' => 4, 'rate' => 29.89, 'start' => now(), 'end' => now()],
            ['employeeId' => 4, 'zoneId' => 5, 'rate' => 30.12, 'start' => now(), 'end' => now()],
            ['employeeId' => 4, 'zoneId' => 6, 'rate' => 30.54, 'start' => now(), 'end' => now()],
            ['employeeId' => 4, 'zoneId' => 7, 'rate' => 30.88, 'start' => now(), 'end' => now()],
            // Lucas Boutonnet
            ['employeeId' => 5, 'zoneId' => 1, 'rate' => 10.93, 'start' => now(), 'end' => now()],
            ['employeeId' => 5, 'zoneId' => 2, 'rate' => 11.11, 'start' => now(), 'end' => now()],
            ['employeeId' => 5, 'zoneId' => 3, 'rate' => 11.42, 'start' => now(), 'end' => now()],
            ['employeeId' => 5, 'zoneId' => 4, 'rate' => 11.60, 'start' => now(), 'end' => now()],
            ['employeeId' => 5, 'zoneId' => 5, 'rate' => 11.84, 'start' => now(), 'end' => now()],
            ['employeeId' => 5, 'zoneId' => 6, 'rate' => 12.28, 'start' => now(), 'end' => now()],
            ['employeeId' => 5, 'zoneId' => 7, 'rate' => 12.64, 'start' => now(), 'end' => now()],
            // Gilson Cabral Robalo
            ['employeeId' => 6, 'zoneId' => 1, 'rate' => 36.26, 'start' => now(), 'end' => now()],
            ['employeeId' => 6, 'zoneId' => 2, 'rate' => 36.43, 'start' => now(), 'end' => now()],
            ['employeeId' => 6, 'zoneId' => 3, 'rate' => 36.72, 'start' => now(), 'end' => now()],
            ['employeeId' => 6, 'zoneId' => 4, 'rate' => 36.89, 'start' => now(), 'end' => now()],
            ['employeeId' => 6, 'zoneId' => 5, 'rate' => 37.12, 'start' => now(), 'end' => now()],
            ['employeeId' => 6, 'zoneId' => 6, 'rate' => 37.53, 'start' => now(), 'end' => now()],
            ['employeeId' => 6, 'zoneId' => 7, 'rate' => 37.88, 'start' => now(), 'end' => now()],
            // Jorge Carvalho
            ['employeeId' => 7, 'zoneId' => 1, 'rate' => 34.92, 'start' => now(), 'end' => now()],
            ['employeeId' => 7, 'zoneId' => 2, 'rate' => 35.09, 'start' => now(), 'end' => now()],
            ['employeeId' => 7, 'zoneId' => 3, 'rate' => 35.38, 'start' => now(), 'end' => now()],
            ['employeeId' => 7, 'zoneId' => 4, 'rate' => 35.55, 'start' => now(), 'end' => now()],
            ['employeeId' => 7, 'zoneId' => 5, 'rate' => 35.78, 'start' => now(), 'end' => now()],
            ['employeeId' => 7, 'zoneId' => 6, 'rate' => 36.19, 'start' => now(), 'end' => now()],
            ['employeeId' => 7, 'zoneId' => 7, 'rate' => 36.54, 'start' => now(), 'end' => now()],
            // Ahmet Cingoz
            ['employeeId' => 8, 'zoneId' => 1, 'rate' => 30.88, 'start' => now(), 'end' => now()],
            ['employeeId' => 8, 'zoneId' => 2, 'rate' => 31.05, 'start' => now(), 'end' => now()],
            ['employeeId' => 8, 'zoneId' => 3, 'rate' => 31.34, 'start' => now(), 'end' => now()],
            ['employeeId' => 8, 'zoneId' => 4, 'rate' => 31.51, 'start' => now(), 'end' => now()],
            ['employeeId' => 8, 'zoneId' => 5, 'rate' => 31.74, 'start' => now(), 'end' => now()],
            ['employeeId' => 8, 'zoneId' => 6, 'rate' => 32.15, 'start' => now(), 'end' => now()],
            ['employeeId' => 8, 'zoneId' => 7, 'rate' => 32.50, 'start' => now(), 'end' => now()],
            // Julien Cochan
            ['employeeId' => 9, 'zoneId' => 1, 'rate' => 38.86, 'start' => now(), 'end' => now()],
            ['employeeId' => 9, 'zoneId' => 2, 'rate' => 39.03, 'start' => now(), 'end' => now()],
            ['employeeId' => 9, 'zoneId' => 3, 'rate' => 39.32, 'start' => now(), 'end' => now()],
            ['employeeId' => 9, 'zoneId' => 4, 'rate' => 39.49, 'start' => now(), 'end' => now()],
            ['employeeId' => 9, 'zoneId' => 5, 'rate' => 39.72, 'start' => now(), 'end' => now()],
            ['employeeId' => 9, 'zoneId' => 6, 'rate' => 40.13, 'start' => now(), 'end' => now()],
            ['employeeId' => 9, 'zoneId' => 7, 'rate' => 40.48, 'start' => now(), 'end' => now()],
            // Steeve Collins
            ['employeeId' => 10, 'zoneId' => 1, 'rate' => 32.76, 'start' => now(), 'end' => now()],
            ['employeeId' => 10, 'zoneId' => 2, 'rate' => 32.93, 'start' => now(), 'end' => now()],
            ['employeeId' => 10, 'zoneId' => 3, 'rate' => 33.22, 'start' => now(), 'end' => now()],
            ['employeeId' => 10, 'zoneId' => 4, 'rate' => 33.39, 'start' => now(), 'end' => now()],
            ['employeeId' => 10, 'zoneId' => 5, 'rate' => 33.62, 'start' => now(), 'end' => now()],
            ['employeeId' => 10, 'zoneId' => 6, 'rate' => 34.03, 'start' => now(), 'end' => now()],
            ['employeeId' => 10, 'zoneId' => 7, 'rate' => 34.38, 'start' => now(), 'end' => now()],
            // Faguimba Coulibaly
            ['employeeId' => 11, 'zoneId' => 1, 'rate' => 28.55, 'start' => now(), 'end' => now()],
            ['employeeId' => 11, 'zoneId' => 2, 'rate' => 28.72, 'start' => now(), 'end' => now()],
            ['employeeId' => 11, 'zoneId' => 3, 'rate' => 29.01, 'start' => now(), 'end' => now()],
            ['employeeId' => 11, 'zoneId' => 4, 'rate' => 29.18, 'start' => now(), 'end' => now()],
            ['employeeId' => 11, 'zoneId' => 5, 'rate' => 29.41, 'start' => now(), 'end' => now()],
            ['employeeId' => 11, 'zoneId' => 6, 'rate' => 29.82, 'start' => now(), 'end' => now()],
            ['employeeId' => 11, 'zoneId' => 7, 'rate' => 30.17, 'start' => now(), 'end' => now()],
            // Lamourou Coulibaly
            ['employeeId' => 12, 'zoneId' => 1, 'rate' => 29.32, 'start' => now(), 'end' => now()],
            ['employeeId' => 12, 'zoneId' => 2, 'rate' => 29.49, 'start' => now(), 'end' => now()],
            ['employeeId' => 12, 'zoneId' => 3, 'rate' => 29.78, 'start' => now(), 'end' => now()],
            ['employeeId' => 12, 'zoneId' => 4, 'rate' => 29.95, 'start' => now(), 'end' => now()],
            ['employeeId' => 12, 'zoneId' => 5, 'rate' => 30.18, 'start' => now(), 'end' => now()],
            ['employeeId' => 12, 'zoneId' => 6, 'rate' => 30.59, 'start' => now(), 'end' => now()],
            ['employeeId' => 12, 'zoneId' => 7, 'rate' => 30.94, 'start' => now(), 'end' => now()],
            // Dominique Couveur
            ['employeeId' => 13, 'zoneId' => 1, 'rate' => 34.92, 'start' => now(), 'end' => now()],
            ['employeeId' => 13, 'zoneId' => 2, 'rate' => 35.09, 'start' => now(), 'end' => now()],
            ['employeeId' => 13, 'zoneId' => 3, 'rate' => 35.38, 'start' => now(), 'end' => now()],
            ['employeeId' => 13, 'zoneId' => 4, 'rate' => 35.55, 'start' => now(), 'end' => now()],
            ['employeeId' => 13, 'zoneId' => 5, 'rate' => 35.78, 'start' => now(), 'end' => now()],
            ['employeeId' => 13, 'zoneId' => 6, 'rate' => 36.19, 'start' => now(), 'end' => now()],
            ['employeeId' => 13, 'zoneId' => 7, 'rate' => 36.54, 'start' => now(), 'end' => now()],
            // Christophe Da Moura
            ['employeeId' => 14, 'zoneId' => 1, 'rate' => 23.78, 'start' => now(), 'end' => now()],
            ['employeeId' => 14, 'zoneId' => 2, 'rate' => 23.95, 'start' => now(), 'end' => now()],
            ['employeeId' => 14, 'zoneId' => 3, 'rate' => 24.24, 'start' => now(), 'end' => now()],
            ['employeeId' => 14, 'zoneId' => 4, 'rate' => 24.41, 'start' => now(), 'end' => now()],
            ['employeeId' => 14, 'zoneId' => 5, 'rate' => 24.64, 'start' => now(), 'end' => now()],
            ['employeeId' => 14, 'zoneId' => 6, 'rate' => 25.06, 'start' => now(), 'end' => now()],
            ['employeeId' => 14, 'zoneId' => 7, 'rate' => 25.40, 'start' => now(), 'end' => now()],
            // Noberto Da Silva
            ['employeeId' => 15, 'zoneId' => 1, 'rate' => 44.85, 'start' => now(), 'end' => now()],
            ['employeeId' => 15, 'zoneId' => 2, 'rate' => 45.02, 'start' => now(), 'end' => now()],
            ['employeeId' => 15, 'zoneId' => 3, 'rate' => 45.31, 'start' => now(), 'end' => now()],
            ['employeeId' => 15, 'zoneId' => 4, 'rate' => 45.48, 'start' => now(), 'end' => now()],
            ['employeeId' => 15, 'zoneId' => 5, 'rate' => 45.71, 'start' => now(), 'end' => now()],
            ['employeeId' => 15, 'zoneId' => 6, 'rate' => 46.12, 'start' => now(), 'end' => now()],
            ['employeeId' => 15, 'zoneId' => 7, 'rate' => 46.47, 'start' => now(), 'end' => now()],
            // José Da Silva Campos
            ['employeeId' => 16, 'zoneId' => 1, 'rate' => 38.21, 'start' => now(), 'end' => now()],
            ['employeeId' => 16, 'zoneId' => 2, 'rate' => 38.39, 'start' => now(), 'end' => now()],
            ['employeeId' => 16, 'zoneId' => 3, 'rate' => 38.67, 'start' => now(), 'end' => now()],
            ['employeeId' => 16, 'zoneId' => 4, 'rate' => 38.84, 'start' => now(), 'end' => now()],
            ['employeeId' => 16, 'zoneId' => 5, 'rate' => 39.07, 'start' => now(), 'end' => now()],
            ['employeeId' => 16, 'zoneId' => 6, 'rate' => 39.49, 'start' => now(), 'end' => now()],
            ['employeeId' => 16, 'zoneId' => 7, 'rate' => 39.83, 'start' => now(), 'end' => now()],
            // Joaquim Da Silva Santos
            ['employeeId' => 17, 'zoneId' => 1, 'rate' => 30.86, 'start' => now(), 'end' => now()],
            ['employeeId' => 17, 'zoneId' => 2, 'rate' => 31.03, 'start' => now(), 'end' => now()],
            ['employeeId' => 17, 'zoneId' => 3, 'rate' => 31.31, 'start' => now(), 'end' => now()],
            ['employeeId' => 17, 'zoneId' => 4, 'rate' => 31.49, 'start' => now(), 'end' => now()],
            ['employeeId' => 17, 'zoneId' => 5, 'rate' => 31.72, 'start' => now(), 'end' => now()],
            ['employeeId' => 17, 'zoneId' => 6, 'rate' => 32.13, 'start' => now(), 'end' => now()],
            ['employeeId' => 17, 'zoneId' => 7, 'rate' => 32.48, 'start' => now(), 'end' => now()],
            // Paulo Jorge Da Silva Vaz
            ['employeeId' => 18, 'zoneId' => 1, 'rate' => 31.69, 'start' => now(), 'end' => now()],
            ['employeeId' => 18, 'zoneId' => 2, 'rate' => 31.86, 'start' => now(), 'end' => now()],
            ['employeeId' => 18, 'zoneId' => 3, 'rate' => 32.15, 'start' => now(), 'end' => now()],
            ['employeeId' => 18, 'zoneId' => 4, 'rate' => 32.32, 'start' => now(), 'end' => now()],
            ['employeeId' => 18, 'zoneId' => 5, 'rate' => 32.55, 'start' => now(), 'end' => now()],
            ['employeeId' => 18, 'zoneId' => 6, 'rate' => 32.97, 'start' => now(), 'end' => now()],
            ['employeeId' => 18, 'zoneId' => 7, 'rate' => 33.31, 'start' => now(), 'end' => now()],
            // Manuel De Lima Fernandes
            ['employeeId' => 19, 'zoneId' => 1, 'rate' => 41.96, 'start' => now(), 'end' => now()],
            ['employeeId' => 19, 'zoneId' => 2, 'rate' => 42.13, 'start' => now(), 'end' => now()],
            ['employeeId' => 19, 'zoneId' => 3, 'rate' => 42.42, 'start' => now(), 'end' => now()],
            ['employeeId' => 19, 'zoneId' => 4, 'rate' => 42.59, 'start' => now(), 'end' => now()],
            ['employeeId' => 19, 'zoneId' => 5, 'rate' => 42.82, 'start' => now(), 'end' => now()],
            ['employeeId' => 19, 'zoneId' => 6, 'rate' => 43.24, 'start' => now(), 'end' => now()],
            ['employeeId' => 19, 'zoneId' => 7, 'rate' => 43.58, 'start' => now(), 'end' => now()],
            // Rui De Oliveira Manco
            ['employeeId' => 20, 'zoneId' => 1, 'rate' => 41.25, 'start' => now(), 'end' => now()],
            ['employeeId' => 20, 'zoneId' => 2, 'rate' => 41.42, 'start' => now(), 'end' => now()],
            ['employeeId' => 20, 'zoneId' => 3, 'rate' => 41.71, 'start' => now(), 'end' => now()],
            ['employeeId' => 20, 'zoneId' => 4, 'rate' => 41.88, 'start' => now(), 'end' => now()],
            ['employeeId' => 20, 'zoneId' => 5, 'rate' => 42.11, 'start' => now(), 'end' => now()],
            ['employeeId' => 20, 'zoneId' => 6, 'rate' => 42.52, 'start' => now(), 'end' => now()],
            ['employeeId' => 20, 'zoneId' => 7, 'rate' => 42.87, 'start' => now(), 'end' => now()],
            // Angelo De Pina Dias
            ['employeeId' => 21, 'zoneId' => 1, 'rate' => 34.83, 'start' => now(), 'end' => now()],
            ['employeeId' => 21, 'zoneId' => 2, 'rate' => 35.00, 'start' => now(), 'end' => now()],
            ['employeeId' => 21, 'zoneId' => 3, 'rate' => 35.29, 'start' => now(), 'end' => now()],
            ['employeeId' => 21, 'zoneId' => 4, 'rate' => 35.46, 'start' => now(), 'end' => now()],
            ['employeeId' => 21, 'zoneId' => 5, 'rate' => 35.69, 'start' => now(), 'end' => now()],
            ['employeeId' => 21, 'zoneId' => 6, 'rate' => 36.11, 'start' => now(), 'end' => now()],
            ['employeeId' => 21, 'zoneId' => 7, 'rate' => 36.45, 'start' => now(), 'end' => now()],
            // Jean Baptiste Delavaud
            ['employeeId' => 22, 'zoneId' => 1, 'rate' => 34.20, 'start' => now(), 'end' => now()],
            ['employeeId' => 22, 'zoneId' => 2, 'rate' => 34.37, 'start' => now(), 'end' => now()],
            ['employeeId' => 22, 'zoneId' => 3, 'rate' => 34.66, 'start' => now(), 'end' => now()],
            ['employeeId' => 22, 'zoneId' => 4, 'rate' => 34.83, 'start' => now(), 'end' => now()],
            ['employeeId' => 22, 'zoneId' => 5, 'rate' => 35.06, 'start' => now(), 'end' => now()],
            ['employeeId' => 22, 'zoneId' => 6, 'rate' => 35.47, 'start' => now(), 'end' => now()],
            ['employeeId' => 22, 'zoneId' => 7, 'rate' => 35.82, 'start' => now(), 'end' => now()],
            // Diakou Dembele
            ['employeeId' => 23, 'zoneId' => 1, 'rate' => 23.78, 'start' => now(), 'end' => now()],
            ['employeeId' => 23, 'zoneId' => 2, 'rate' => 23.95, 'start' => now(), 'end' => now()],
            ['employeeId' => 23, 'zoneId' => 3, 'rate' => 24.24, 'start' => now(), 'end' => now()],
            ['employeeId' => 23, 'zoneId' => 4, 'rate' => 24.41, 'start' => now(), 'end' => now()],
            ['employeeId' => 23, 'zoneId' => 5, 'rate' => 24.64, 'start' => now(), 'end' => now()],
            ['employeeId' => 23, 'zoneId' => 6, 'rate' => 25.06, 'start' => now(), 'end' => now()],
            ['employeeId' => 23, 'zoneId' => 7, 'rate' => 25.40, 'start' => now(), 'end' => now()],
            // Fabien Demigny
            ['employeeId' => 24, 'zoneId' => 1, 'rate' => 36.61, 'start' => now(), 'end' => now()],
            ['employeeId' => 24, 'zoneId' => 2, 'rate' => 36.79, 'start' => now(), 'end' => now()],
            ['employeeId' => 24, 'zoneId' => 3, 'rate' => 37.07, 'start' => now(), 'end' => now()],
            ['employeeId' => 24, 'zoneId' => 4, 'rate' => 37.25, 'start' => now(), 'end' => now()],
            ['employeeId' => 24, 'zoneId' => 5, 'rate' => 37.48, 'start' => now(), 'end' => now()],
            ['employeeId' => 24, 'zoneId' => 6, 'rate' => 37.89, 'start' => now(), 'end' => now()],
            ['employeeId' => 24, 'zoneId' => 7, 'rate' => 38.23, 'start' => now(), 'end' => now()],
            // Mama Diarra
            ['employeeId' => 25, 'zoneId' => 1, 'rate' => 23.78, 'start' => now(), 'end' => now()],
            ['employeeId' => 25, 'zoneId' => 2, 'rate' => 23.95, 'start' => now(), 'end' => now()],
            ['employeeId' => 25, 'zoneId' => 3, 'rate' => 24.24, 'start' => now(), 'end' => now()],
            ['employeeId' => 25, 'zoneId' => 4, 'rate' => 24.41, 'start' => now(), 'end' => now()],
            ['employeeId' => 25, 'zoneId' => 5, 'rate' => 24.64, 'start' => now(), 'end' => now()],
            ['employeeId' => 25, 'zoneId' => 6, 'rate' => 25.06, 'start' => now(), 'end' => now()],
            ['employeeId' => 25, 'zoneId' => 7, 'rate' => 25.40, 'start' => now(), 'end' => now()],
            // Elias Dos Santos
            ['employeeId' => 26, 'zoneId' => 1, 'rate' => 34.58, 'start' => now(), 'end' => now()],
            ['employeeId' => 26, 'zoneId' => 2, 'rate' => 34.76, 'start' => now(), 'end' => now()],
            ['employeeId' => 26, 'zoneId' => 3, 'rate' => 35.04, 'start' => now(), 'end' => now()],
            ['employeeId' => 26, 'zoneId' => 4, 'rate' => 35.22, 'start' => now(), 'end' => now()],
            ['employeeId' => 26, 'zoneId' => 5, 'rate' => 35.45, 'start' => now(), 'end' => now()],
            ['employeeId' => 26, 'zoneId' => 6, 'rate' => 35.86, 'start' => now(), 'end' => now()],
            ['employeeId' => 26, 'zoneId' => 7, 'rate' => 36.20, 'start' => now(), 'end' => now()],
            // Alvarino Duarte Da Moura
            ['employeeId' => 27, 'zoneId' => 1, 'rate' => 36.03, 'start' => now(), 'end' => now()],
            ['employeeId' => 27, 'zoneId' => 2, 'rate' => 36.20, 'start' => now(), 'end' => now()],
            ['employeeId' => 27, 'zoneId' => 3, 'rate' => 36.49, 'start' => now(), 'end' => now()],
            ['employeeId' => 27, 'zoneId' => 4, 'rate' => 36.66, 'start' => now(), 'end' => now()],
            ['employeeId' => 27, 'zoneId' => 5, 'rate' => 36.89, 'start' => now(), 'end' => now()],
            ['employeeId' => 27, 'zoneId' => 6, 'rate' => 37.31, 'start' => now(), 'end' => now()],
            ['employeeId' => 27, 'zoneId' => 7, 'rate' => 37.65, 'start' => now(), 'end' => now()],
            // Nicolas Esnault
            ['employeeId' => 28, 'zoneId' => 1, 'rate' => 35.86, 'start' => now(), 'end' => now()],
            ['employeeId' => 28, 'zoneId' => 2, 'rate' => 36.03, 'start' => now(), 'end' => now()],
            ['employeeId' => 28, 'zoneId' => 3, 'rate' => 36.32, 'start' => now(), 'end' => now()],
            ['employeeId' => 28, 'zoneId' => 4, 'rate' => 36.49, 'start' => now(), 'end' => now()],
            ['employeeId' => 28, 'zoneId' => 5, 'rate' => 36.72, 'start' => now(), 'end' => now()],
            ['employeeId' => 28, 'zoneId' => 6, 'rate' => 37.14, 'start' => now(), 'end' => now()],
            ['employeeId' => 28, 'zoneId' => 7, 'rate' => 37.48, 'start' => now(), 'end' => now()],
            // Ludovic Fernandes
            ['employeeId' => 29, 'zoneId' => 1, 'rate' => 39.36, 'start' => now(), 'end' => now()],
            ['employeeId' => 29, 'zoneId' => 2, 'rate' => 39.53, 'start' => now(), 'end' => now()],
            ['employeeId' => 29, 'zoneId' => 3, 'rate' => 39.82, 'start' => now(), 'end' => now()],
            ['employeeId' => 29, 'zoneId' => 4, 'rate' => 39.99, 'start' => now(), 'end' => now()],
            ['employeeId' => 29, 'zoneId' => 5, 'rate' => 40.22, 'start' => now(), 'end' => now()],
            ['employeeId' => 29, 'zoneId' => 6, 'rate' => 40.64, 'start' => now(), 'end' => now()],
            ['employeeId' => 29, 'zoneId' => 7, 'rate' => 40.98, 'start' => now(), 'end' => now()],
            // Christophe Fernandes
            ['employeeId' => 30, 'zoneId' => 1, 'rate' => 47.43, 'start' => now(), 'end' => now()],
            ['employeeId' => 30, 'zoneId' => 2, 'rate' => 47.43, 'start' => now(), 'end' => now()],
            ['employeeId' => 30, 'zoneId' => 3, 'rate' => 47.43, 'start' => now(), 'end' => now()],
            ['employeeId' => 30, 'zoneId' => 4, 'rate' => 47.43, 'start' => now(), 'end' => now()],
            ['employeeId' => 30, 'zoneId' => 5, 'rate' => 47.43, 'start' => now(), 'end' => now()],
            ['employeeId' => 30, 'zoneId' => 6, 'rate' => 47.43, 'start' => now(), 'end' => now()],
            ['employeeId' => 30, 'zoneId' => 7, 'rate' => 47.43, 'start' => now(), 'end' => now()],
            // Antonio Fernandes
            ['employeeId' => 31, 'zoneId' => 1, 'rate' => 49.07, 'start' => now(), 'end' => now()],
            ['employeeId' => 31, 'zoneId' => 2, 'rate' => 49.24, 'start' => now(), 'end' => now()],
            ['employeeId' => 31, 'zoneId' => 3, 'rate' => 49.53, 'start' => now(), 'end' => now()],
            ['employeeId' => 31, 'zoneId' => 4, 'rate' => 49.70, 'start' => now(), 'end' => now()],
            ['employeeId' => 31, 'zoneId' => 5, 'rate' => 49.93, 'start' => now(), 'end' => now()],
            ['employeeId' => 31, 'zoneId' => 6, 'rate' => 50.34, 'start' => now(), 'end' => now()],
            ['employeeId' => 31, 'zoneId' => 7, 'rate' => 50.69, 'start' => now(), 'end' => now()],
            // Joao Flora Alves
            ['employeeId' => 32, 'zoneId' => 1, 'rate' => 42.57, 'start' => now(), 'end' => now()],
            ['employeeId' => 32, 'zoneId' => 2, 'rate' => 42.75, 'start' => now(), 'end' => now()],
            ['employeeId' => 32, 'zoneId' => 3, 'rate' => 43.03, 'start' => now(), 'end' => now()],
            ['employeeId' => 32, 'zoneId' => 4, 'rate' => 43.21, 'start' => now(), 'end' => now()],
            ['employeeId' => 32, 'zoneId' => 5, 'rate' => 43.44, 'start' => now(), 'end' => now()],
            ['employeeId' => 32, 'zoneId' => 6, 'rate' => 43.85, 'start' => now(), 'end' => now()],
            ['employeeId' => 32, 'zoneId' => 7, 'rate' => 44.19, 'start' => now(), 'end' => now()],
            // Christophe Germond
            ['employeeId' => 33, 'zoneId' => 1, 'rate' => 38.50, 'start' => now(), 'end' => now()],
            ['employeeId' => 33, 'zoneId' => 2, 'rate' => 38.67, 'start' => now(), 'end' => now()],
            ['employeeId' => 33, 'zoneId' => 3, 'rate' => 38.96, 'start' => now(), 'end' => now()],
            ['employeeId' => 33, 'zoneId' => 4, 'rate' => 39.13, 'start' => now(), 'end' => now()],
            ['employeeId' => 33, 'zoneId' => 5, 'rate' => 39.36, 'start' => now(), 'end' => now()],
            ['employeeId' => 33, 'zoneId' => 6, 'rate' => 39.77, 'start' => now(), 'end' => now()],
            ['employeeId' => 33, 'zoneId' => 7, 'rate' => 40.12, 'start' => now(), 'end' => now()],
            // Domingos Gomes
            ['employeeId' => 34, 'zoneId' => 1, 'rate' => 63.38, 'start' => now(), 'end' => now()],
            ['employeeId' => 34, 'zoneId' => 2, 'rate' => 63.68, 'start' => now(), 'end' => now()],
            ['employeeId' => 34, 'zoneId' => 3, 'rate' => 63.38, 'start' => now(), 'end' => now()],
            ['employeeId' => 34, 'zoneId' => 4, 'rate' => 63.38, 'start' => now(), 'end' => now()],
            ['employeeId' => 34, 'zoneId' => 5, 'rate' => 63.38, 'start' => now(), 'end' => now()],
            ['employeeId' => 34, 'zoneId' => 6, 'rate' => 63.38, 'start' => now(), 'end' => now()],
            ['employeeId' => 34, 'zoneId' => 7, 'rate' => 63.38, 'start' => now(), 'end' => now()],
            // José Manuel Gomes Pacheco
            ['employeeId' => 35, 'zoneId' => 1, 'rate' => 40.12, 'start' => now(), 'end' => now()],
            ['employeeId' => 35, 'zoneId' => 2, 'rate' => 40.30, 'start' => now(), 'end' => now()],
            ['employeeId' => 35, 'zoneId' => 3, 'rate' => 40.58, 'start' => now(), 'end' => now()],
            ['employeeId' => 35, 'zoneId' => 4, 'rate' => 40.76, 'start' => now(), 'end' => now()],
            ['employeeId' => 35, 'zoneId' => 5, 'rate' => 40.98, 'start' => now(), 'end' => now()],
            ['employeeId' => 35, 'zoneId' => 6, 'rate' => 41.40, 'start' => now(), 'end' => now()],
            ['employeeId' => 35, 'zoneId' => 7, 'rate' => 41.74, 'start' => now(), 'end' => now()],
            // Jorge Goncalves
            ['employeeId' => 36, 'zoneId' => 1, 'rate' => 39.66, 'start' => now(), 'end' => now()],
            ['employeeId' => 36, 'zoneId' => 2, 'rate' => 39.83, 'start' => now(), 'end' => now()],
            ['employeeId' => 36, 'zoneId' => 3, 'rate' => 40.12, 'start' => now(), 'end' => now()],
            ['employeeId' => 36, 'zoneId' => 4, 'rate' => 40.29, 'start' => now(), 'end' => now()],
            ['employeeId' => 36, 'zoneId' => 5, 'rate' => 40.52, 'start' => now(), 'end' => now()],
            ['employeeId' => 36, 'zoneId' => 6, 'rate' => 40.93, 'start' => now(), 'end' => now()],
            ['employeeId' => 36, 'zoneId' => 7, 'rate' => 41.28, 'start' => now(), 'end' => now()],
            // Guillaume Gourdon
            ['employeeId' => 37, 'zoneId' => 1, 'rate' => 39.81, 'start' => now(), 'end' => now()],
            ['employeeId' => 37, 'zoneId' => 2, 'rate' => 39.98, 'start' => now(), 'end' => now()],
            ['employeeId' => 37, 'zoneId' => 3, 'rate' => 40.27, 'start' => now(), 'end' => now()],
            ['employeeId' => 37, 'zoneId' => 4, 'rate' => 40.44, 'start' => now(), 'end' => now()],
            ['employeeId' => 37, 'zoneId' => 5, 'rate' => 40.67, 'start' => now(), 'end' => now()],
            ['employeeId' => 37, 'zoneId' => 6, 'rate' => 41.09, 'start' => now(), 'end' => now()],
            ['employeeId' => 37, 'zoneId' => 7, 'rate' => 41.43, 'start' => now(), 'end' => now()],
            // Férit Kapusuk
            ['employeeId' => 38, 'zoneId' => 1, 'rate' => 32.63, 'start' => now(), 'end' => now()],
            ['employeeId' => 38, 'zoneId' => 2, 'rate' => 32.80, 'start' => now(), 'end' => now()],
            ['employeeId' => 38, 'zoneId' => 3, 'rate' => 33.09, 'start' => now(), 'end' => now()],
            ['employeeId' => 38, 'zoneId' => 4, 'rate' => 33.26, 'start' => now(), 'end' => now()],
            ['employeeId' => 38, 'zoneId' => 5, 'rate' => 33.49, 'start' => now(), 'end' => now()],
            ['employeeId' => 38, 'zoneId' => 6, 'rate' => 33.90, 'start' => now(), 'end' => now()],
            ['employeeId' => 38, 'zoneId' => 7, 'rate' => 34.25, 'start' => now(), 'end' => now()],
            // Sergio Lopes
            ['employeeId' => 39, 'zoneId' => 1, 'rate' => 27.80, 'start' => now(), 'end' => now()],
            ['employeeId' => 39, 'zoneId' => 2, 'rate' => 27.98, 'start' => now(), 'end' => now()],
            ['employeeId' => 39, 'zoneId' => 3, 'rate' => 28.26, 'start' => now(), 'end' => now()],
            ['employeeId' => 39, 'zoneId' => 4, 'rate' => 28.44, 'start' => now(), 'end' => now()],
            ['employeeId' => 39, 'zoneId' => 5, 'rate' => 28.66, 'start' => now(), 'end' => now()],
            ['employeeId' => 39, 'zoneId' => 6, 'rate' => 29.08, 'start' => now(), 'end' => now()],
            ['employeeId' => 39, 'zoneId' => 7, 'rate' => 29.42, 'start' => now(), 'end' => now()],
            // Paulo Lourenco
            ['employeeId' => 40, 'zoneId' => 1, 'rate' => 33.44, 'start' => now(), 'end' => now()],
            ['employeeId' => 40, 'zoneId' => 2, 'rate' => 33.61, 'start' => now(), 'end' => now()],
            ['employeeId' => 40, 'zoneId' => 3, 'rate' => 33.90, 'start' => now(), 'end' => now()],
            ['employeeId' => 40, 'zoneId' => 4, 'rate' => 34.07, 'start' => now(), 'end' => now()],
            ['employeeId' => 40, 'zoneId' => 5, 'rate' => 34.30, 'start' => now(), 'end' => now()],
            ['employeeId' => 40, 'zoneId' => 6, 'rate' => 34.72, 'start' => now(), 'end' => now()],
            ['employeeId' => 40, 'zoneId' => 7, 'rate' => 35.06, 'start' => now(), 'end' => now()],
            // Cheikhou Magassa
            ['employeeId' => 41, 'zoneId' => 1, 'rate' => 28.55, 'start' => now(), 'end' => now()],
            ['employeeId' => 41, 'zoneId' => 2, 'rate' => 28.72, 'start' => now(), 'end' => now()],
            ['employeeId' => 41, 'zoneId' => 3, 'rate' => 29.01, 'start' => now(), 'end' => now()],
            ['employeeId' => 41, 'zoneId' => 4, 'rate' => 29.18, 'start' => now(), 'end' => now()],
            ['employeeId' => 41, 'zoneId' => 5, 'rate' => 29.41, 'start' => now(), 'end' => now()],
            ['employeeId' => 41, 'zoneId' => 6, 'rate' => 29.82, 'start' => now(), 'end' => now()],
            ['employeeId' => 41, 'zoneId' => 7, 'rate' => 30.17, 'start' => now(), 'end' => now()],
            // Carlos Malheiro
            ['employeeId' => 42, 'zoneId' => 1, 'rate' => 42.47, 'start' => now(), 'end' => now()],
            ['employeeId' => 42, 'zoneId' => 2, 'rate' => 42.47, 'start' => now(), 'end' => now()],
            ['employeeId' => 42, 'zoneId' => 3, 'rate' => 42.47, 'start' => now(), 'end' => now()],
            ['employeeId' => 42, 'zoneId' => 4, 'rate' => 42.47, 'start' => now(), 'end' => now()],
            ['employeeId' => 42, 'zoneId' => 5, 'rate' => 42.47, 'start' => now(), 'end' => now()],
            ['employeeId' => 42, 'zoneId' => 6, 'rate' => 42.47, 'start' => now(), 'end' => now()],
            ['employeeId' => 42, 'zoneId' => 7, 'rate' => 42.47, 'start' => now(), 'end' => now()],
            // Tacettin Maraslioglu
            ['employeeId' => 43, 'zoneId' => 1, 'rate' => 38.66, 'start' => now(), 'end' => now()],
            ['employeeId' => 43, 'zoneId' => 2, 'rate' => 38.84, 'start' => now(), 'end' => now()],
            ['employeeId' => 43, 'zoneId' => 3, 'rate' => 39.12, 'start' => now(), 'end' => now()],
            ['employeeId' => 43, 'zoneId' => 4, 'rate' => 39.30, 'start' => now(), 'end' => now()],
            ['employeeId' => 43, 'zoneId' => 5, 'rate' => 39.53, 'start' => now(), 'end' => now()],
            ['employeeId' => 43, 'zoneId' => 6, 'rate' => 39.94, 'start' => now(), 'end' => now()],
            ['employeeId' => 43, 'zoneId' => 7, 'rate' => 40.28, 'start' => now(), 'end' => now()],
            // Cyril Martinez
            ['employeeId' => 44, 'zoneId' => 1, 'rate' => 35.37, 'start' => now(), 'end' => now()],
            ['employeeId' => 44, 'zoneId' => 2, 'rate' => 35.55, 'start' => now(), 'end' => now()],
            ['employeeId' => 44, 'zoneId' => 3, 'rate' => 35.83, 'start' => now(), 'end' => now()],
            ['employeeId' => 44, 'zoneId' => 4, 'rate' => 36.01, 'start' => now(), 'end' => now()],
            ['employeeId' => 44, 'zoneId' => 5, 'rate' => 36.24, 'start' => now(), 'end' => now()],
            ['employeeId' => 44, 'zoneId' => 6, 'rate' => 36.65, 'start' => now(), 'end' => now()],
            ['employeeId' => 44, 'zoneId' => 7, 'rate' => 36.99, 'start' => now(), 'end' => now()],
            // Joao Mendes De Brito
            ['employeeId' => 45, 'zoneId' => 1, 'rate' => 31.39, 'start' => now(), 'end' => now()],
            ['employeeId' => 45, 'zoneId' => 2, 'rate' => 31.56, 'start' => now(), 'end' => now()],
            ['employeeId' => 45, 'zoneId' => 3, 'rate' => 31.85, 'start' => now(), 'end' => now()],
            ['employeeId' => 45, 'zoneId' => 4, 'rate' => 32.02, 'start' => now(), 'end' => now()],
            ['employeeId' => 45, 'zoneId' => 5, 'rate' => 32.25, 'start' => now(), 'end' => now()],
            ['employeeId' => 45, 'zoneId' => 6, 'rate' => 32.66, 'start' => now(), 'end' => now()],
            ['employeeId' => 45, 'zoneId' => 7, 'rate' => 33.01, 'start' => now(), 'end' => now()],
            // Stéphane Michaut
            ['employeeId' => 46, 'zoneId' => 1, 'rate' => 28.92, 'start' => now(), 'end' => now()],
            ['employeeId' => 46, 'zoneId' => 2, 'rate' => 29.09, 'start' => now(), 'end' => now()],
            ['employeeId' => 46, 'zoneId' => 3, 'rate' => 29.38, 'start' => now(), 'end' => now()],
            ['employeeId' => 46, 'zoneId' => 4, 'rate' => 29.55, 'start' => now(), 'end' => now()],
            ['employeeId' => 46, 'zoneId' => 5, 'rate' => 29.78, 'start' => now(), 'end' => now()],
            ['employeeId' => 46, 'zoneId' => 6, 'rate' => 30.20, 'start' => now(), 'end' => now()],
            ['employeeId' => 46, 'zoneId' => 7, 'rate' => 30.54, 'start' => now(), 'end' => now()],
            // Théo Noel
            ['employeeId' => 47, 'zoneId' => 1, 'rate' => 18.76, 'start' => now(), 'end' => now()],
            ['employeeId' => 47, 'zoneId' => 2, 'rate' => 18.95, 'start' => now(), 'end' => now()],
            ['employeeId' => 47, 'zoneId' => 3, 'rate' => 19.25, 'start' => now(), 'end' => now()],
            ['employeeId' => 47, 'zoneId' => 4, 'rate' => 19.43, 'start' => now(), 'end' => now()],
            ['employeeId' => 47, 'zoneId' => 5, 'rate' => 19.67, 'start' => now(), 'end' => now()],
            ['employeeId' => 47, 'zoneId' => 6, 'rate' => 20.11, 'start' => now(), 'end' => now()],
            ['employeeId' => 47, 'zoneId' => 7, 'rate' => 20.48, 'start' => now(), 'end' => now()],
            // Rayyan Ouerfelli
            ['employeeId' => 48, 'zoneId' => 1, 'rate' => 12.85, 'start' => now(), 'end' => now()],
            ['employeeId' => 48, 'zoneId' => 2, 'rate' => 13.03, 'start' => now(), 'end' => now()],
            ['employeeId' => 48, 'zoneId' => 3, 'rate' => 13.31, 'start' => now(), 'end' => now()],
            ['employeeId' => 48, 'zoneId' => 4, 'rate' => 13.49, 'start' => now(), 'end' => now()],
            ['employeeId' => 48, 'zoneId' => 5, 'rate' => 13.72, 'start' => now(), 'end' => now()],
            ['employeeId' => 48, 'zoneId' => 6, 'rate' => 14.13, 'start' => now(), 'end' => now()],
            ['employeeId' => 48, 'zoneId' => 7, 'rate' => 14.47, 'start' => now(), 'end' => now()],
            // Ahmet Ozdamar
            ['employeeId' => 49, 'zoneId' => 1, 'rate' => 31.51, 'start' => now(), 'end' => now()],
            ['employeeId' => 49, 'zoneId' => 2, 'rate' => 31.69, 'start' => now(), 'end' => now()],
            ['employeeId' => 49, 'zoneId' => 3, 'rate' => 31.97, 'start' => now(), 'end' => now()],
            ['employeeId' => 49, 'zoneId' => 4, 'rate' => 32.15, 'start' => now(), 'end' => now()],
            ['employeeId' => 49, 'zoneId' => 5, 'rate' => 32.38, 'start' => now(), 'end' => now()],
            ['employeeId' => 49, 'zoneId' => 6, 'rate' => 32.79, 'start' => now(), 'end' => now()],
            ['employeeId' => 49, 'zoneId' => 7, 'rate' => 33.13, 'start' => now(), 'end' => now()],
            // Joao Passeira
            ['employeeId' => 50, 'zoneId' => 1, 'rate' => 36.73, 'start' => now(), 'end' => now()],
            ['employeeId' => 50, 'zoneId' => 2, 'rate' => 36.90, 'start' => now(), 'end' => now()],
            ['employeeId' => 50, 'zoneId' => 3, 'rate' => 37.19, 'start' => now(), 'end' => now()],
            ['employeeId' => 50, 'zoneId' => 4, 'rate' => 37.36, 'start' => now(), 'end' => now()],
            ['employeeId' => 50, 'zoneId' => 5, 'rate' => 37.59, 'start' => now(), 'end' => now()],
            ['employeeId' => 50, 'zoneId' => 6, 'rate' => 38.00, 'start' => now(), 'end' => now()],
            ['employeeId' => 50, 'zoneId' => 7, 'rate' => 38.35, 'start' => now(), 'end' => now()],
            // Antonino Pinto Da Silva
            ['employeeId' => 51, 'zoneId' => 1, 'rate' => 38.14, 'start' => now(), 'end' => now()],
            ['employeeId' => 51, 'zoneId' => 2, 'rate' => 38.31, 'start' => now(), 'end' => now()],
            ['employeeId' => 51, 'zoneId' => 3, 'rate' => 38.59, 'start' => now(), 'end' => now()],
            ['employeeId' => 51, 'zoneId' => 4, 'rate' => 38.77, 'start' => now(), 'end' => now()],
            ['employeeId' => 51, 'zoneId' => 5, 'rate' => 39.00, 'start' => now(), 'end' => now()],
            ['employeeId' => 51, 'zoneId' => 6, 'rate' => 39.41, 'start' => now(), 'end' => now()],
            ['employeeId' => 51, 'zoneId' => 7, 'rate' => 39.75, 'start' => now(), 'end' => now()],
            // Alexandre Poupry
            ['employeeId' => 52, 'zoneId' => 1, 'rate' => 34.76, 'start' => now(), 'end' => now()],
            ['employeeId' => 52, 'zoneId' => 2, 'rate' => 34.93, 'start' => now(), 'end' => now()],
            ['employeeId' => 52, 'zoneId' => 3, 'rate' => 35.22, 'start' => now(), 'end' => now()],
            ['employeeId' => 52, 'zoneId' => 4, 'rate' => 35.39, 'start' => now(), 'end' => now()],
            ['employeeId' => 52, 'zoneId' => 5, 'rate' => 35.62, 'start' => now(), 'end' => now()],
            ['employeeId' => 52, 'zoneId' => 6, 'rate' => 36.03, 'start' => now(), 'end' => now()],
            ['employeeId' => 52, 'zoneId' => 7, 'rate' => 36.38, 'start' => now(), 'end' => now()],
            // David Rodrigues
            ['employeeId' => 53, 'zoneId' => 1, 'rate' => 43.22, 'start' => now(), 'end' => now()],
            ['employeeId' => 53, 'zoneId' => 2, 'rate' => 43.22, 'start' => now(), 'end' => now()],
            ['employeeId' => 53, 'zoneId' => 3, 'rate' => 43.22, 'start' => now(), 'end' => now()],
            ['employeeId' => 53, 'zoneId' => 4, 'rate' => 43.22, 'start' => now(), 'end' => now()],
            ['employeeId' => 53, 'zoneId' => 5, 'rate' => 43.22, 'start' => now(), 'end' => now()],
            ['employeeId' => 53, 'zoneId' => 6, 'rate' => 43.22, 'start' => now(), 'end' => now()],
            ['employeeId' => 53, 'zoneId' => 7, 'rate' => 43.22, 'start' => now(), 'end' => now()],
            // Noé Rodrigues
            ['employeeId' => 54, 'zoneId' => 1, 'rate' => 43.22, 'start' => now(), 'end' => now()],
            ['employeeId' => 54, 'zoneId' => 2, 'rate' => 43.22, 'start' => now(), 'end' => now()],
            ['employeeId' => 54, 'zoneId' => 3, 'rate' => 43.22, 'start' => now(), 'end' => now()],
            ['employeeId' => 54, 'zoneId' => 4, 'rate' => 43.22, 'start' => now(), 'end' => now()],
            ['employeeId' => 54, 'zoneId' => 5, 'rate' => 43.22, 'start' => now(), 'end' => now()],
            ['employeeId' => 54, 'zoneId' => 6, 'rate' => 43.22, 'start' => now(), 'end' => now()],
            ['employeeId' => 54, 'zoneId' => 7, 'rate' => 43.22, 'start' => now(), 'end' => now()],
            // Eusébio Semedo Moreira
            ['employeeId' => 55, 'zoneId' => 1, 'rate' => 27.36, 'start' => now(), 'end' => now()],
            ['employeeId' => 55, 'zoneId' => 2, 'rate' => 27.53, 'start' => now(), 'end' => now()],
            ['employeeId' => 55, 'zoneId' => 3, 'rate' => 27.82, 'start' => now(), 'end' => now()],
            ['employeeId' => 55, 'zoneId' => 4, 'rate' => 27.99, 'start' => now(), 'end' => now()],
            ['employeeId' => 55, 'zoneId' => 5, 'rate' => 28.22, 'start' => now(), 'end' => now()],
            ['employeeId' => 55, 'zoneId' => 6, 'rate' => 28.63, 'start' => now(), 'end' => now()],
            ['employeeId' => 55, 'zoneId' => 7, 'rate' => 28.98, 'start' => now(), 'end' => now()],
            // Félisberto Semedo Cabral
            ['employeeId' => 56, 'zoneId' => 1, 'rate' => 36.24, 'start' => now(), 'end' => now()],
            ['employeeId' => 56, 'zoneId' => 2, 'rate' => 36.42, 'start' => now(), 'end' => now()],
            ['employeeId' => 56, 'zoneId' => 3, 'rate' => 36.70, 'start' => now(), 'end' => now()],
            ['employeeId' => 56, 'zoneId' => 4, 'rate' => 36.88, 'start' => now(), 'end' => now()],
            ['employeeId' => 56, 'zoneId' => 5, 'rate' => 37.10, 'start' => now(), 'end' => now()],
            ['employeeId' => 56, 'zoneId' => 6, 'rate' => 37.52, 'start' => now(), 'end' => now()],
            ['employeeId' => 56, 'zoneId' => 7, 'rate' => 37.86, 'start' => now(), 'end' => now()],
            // Damien Sevestre
            ['employeeId' => 57, 'zoneId' => 1, 'rate' => 28.37, 'start' => now(), 'end' => now()],
            ['employeeId' => 57, 'zoneId' => 2, 'rate' => 28.55, 'start' => now(), 'end' => now()],
            ['employeeId' => 57, 'zoneId' => 3, 'rate' => 28.83, 'start' => now(), 'end' => now()],
            ['employeeId' => 57, 'zoneId' => 4, 'rate' => 29.01, 'start' => now(), 'end' => now()],
            ['employeeId' => 57, 'zoneId' => 5, 'rate' => 29.23, 'start' => now(), 'end' => now()],
            ['employeeId' => 57, 'zoneId' => 6, 'rate' => 29.65, 'start' => now(), 'end' => now()],
            ['employeeId' => 57, 'zoneId' => 7, 'rate' => 29.99, 'start' => now(), 'end' => now()],
            // Drissa Sidibe
            ['employeeId' => 58, 'zoneId' => 1, 'rate' => 35.09, 'start' => now(), 'end' => now()],
            ['employeeId' => 58, 'zoneId' => 2, 'rate' => 35.27, 'start' => now(), 'end' => now()],
            ['employeeId' => 58, 'zoneId' => 3, 'rate' => 35.55, 'start' => now(), 'end' => now()],
            ['employeeId' => 58, 'zoneId' => 4, 'rate' => 35.73, 'start' => now(), 'end' => now()],
            ['employeeId' => 58, 'zoneId' => 5, 'rate' => 35.96, 'start' => now(), 'end' => now()],
            ['employeeId' => 58, 'zoneId' => 6, 'rate' => 36.37, 'start' => now(), 'end' => now()],
            ['employeeId' => 58, 'zoneId' => 7, 'rate' => 36.71, 'start' => now(), 'end' => now()],
            // Luis Simoes
            ['employeeId' => 59, 'zoneId' => 1, 'rate' => 40.50, 'start' => now(), 'end' => now()],
            ['employeeId' => 59, 'zoneId' => 2, 'rate' => 40.67, 'start' => now(), 'end' => now()],
            ['employeeId' => 59, 'zoneId' => 3, 'rate' => 40.96, 'start' => now(), 'end' => now()],
            ['employeeId' => 59, 'zoneId' => 4, 'rate' => 41.13, 'start' => now(), 'end' => now()],
            ['employeeId' => 59, 'zoneId' => 5, 'rate' => 41.36, 'start' => now(), 'end' => now()],
            ['employeeId' => 59, 'zoneId' => 6, 'rate' => 41.77, 'start' => now(), 'end' => now()],
            ['employeeId' => 59, 'zoneId' => 7, 'rate' => 42.12, 'start' => now(), 'end' => now()],
            // Zamfir Stinga
            ['employeeId' => 60, 'zoneId' => 1, 'rate' => 31.88, 'start' => now(), 'end' => now()],
            ['employeeId' => 60, 'zoneId' => 2, 'rate' => 32.05, 'start' => now(), 'end' => now()],
            ['employeeId' => 60, 'zoneId' => 3, 'rate' => 32.33, 'start' => now(), 'end' => now()],
            ['employeeId' => 60, 'zoneId' => 4, 'rate' => 32.51, 'start' => now(), 'end' => now()],
            ['employeeId' => 60, 'zoneId' => 5, 'rate' => 32.74, 'start' => now(), 'end' => now()],
            ['employeeId' => 60, 'zoneId' => 6, 'rate' => 33.15, 'start' => now(), 'end' => now()],
            ['employeeId' => 60, 'zoneId' => 7, 'rate' => 33.49, 'start' => now(), 'end' => now()],
            // Abdoulaye Toure
            ['employeeId' => 61, 'zoneId' => 1, 'rate' => 28.65, 'start' => now(), 'end' => now()],
            ['employeeId' => 61, 'zoneId' => 2, 'rate' => 28.82, 'start' => now(), 'end' => now()],
            ['employeeId' => 61, 'zoneId' => 3, 'rate' => 29.11, 'start' => now(), 'end' => now()],
            ['employeeId' => 61, 'zoneId' => 4, 'rate' => 29.28, 'start' => now(), 'end' => now()],
            ['employeeId' => 61, 'zoneId' => 5, 'rate' => 29.51, 'start' => now(), 'end' => now()],
            ['employeeId' => 61, 'zoneId' => 6, 'rate' => 29.92, 'start' => now(), 'end' => now()],
            ['employeeId' => 61, 'zoneId' => 7, 'rate' => 30.27, 'start' => now(), 'end' => now()],
            // Diadie Traore
            ['employeeId' => 62, 'zoneId' => 1, 'rate' => 23.97, 'start' => now(), 'end' => now()],
            ['employeeId' => 62, 'zoneId' => 2, 'rate' => 24.14, 'start' => now(), 'end' => now()],
            ['employeeId' => 62, 'zoneId' => 3, 'rate' => 24.43, 'start' => now(), 'end' => now()],
            ['employeeId' => 62, 'zoneId' => 4, 'rate' => 24.60, 'start' => now(), 'end' => now()],
            ['employeeId' => 62, 'zoneId' => 5, 'rate' => 24.83, 'start' => now(), 'end' => now()],
            ['employeeId' => 62, 'zoneId' => 6, 'rate' => 25.25, 'start' => now(), 'end' => now()],
            ['employeeId' => 62, 'zoneId' => 7, 'rate' => 25.59, 'start' => now(), 'end' => now()],
            // Murat Ulusan
            ['employeeId' => 63, 'zoneId' => 1, 'rate' => 29.83, 'start' => now(), 'end' => now()],
            ['employeeId' => 63, 'zoneId' => 2, 'rate' => 30.00, 'start' => now(), 'end' => now()],
            ['employeeId' => 63, 'zoneId' => 3, 'rate' => 30.29, 'start' => now(), 'end' => now()],
            ['employeeId' => 63, 'zoneId' => 4, 'rate' => 30.46, 'start' => now(), 'end' => now()],
            ['employeeId' => 63, 'zoneId' => 5, 'rate' => 30.69, 'start' => now(), 'end' => now()],
            ['employeeId' => 63, 'zoneId' => 6, 'rate' => 31.10, 'start' => now(), 'end' => now()],
            ['employeeId' => 63, 'zoneId' => 7, 'rate' => 31.45, 'start' => now(), 'end' => now()],
            // Isa Uysal
            ['employeeId' => 64, 'zoneId' => 1, 'rate' => 38.76, 'start' => now(), 'end' => now()],
            ['employeeId' => 64, 'zoneId' => 2, 'rate' => 38.94, 'start' => now(), 'end' => now()],
            ['employeeId' => 64, 'zoneId' => 3, 'rate' => 39.22, 'start' => now(), 'end' => now()],
            ['employeeId' => 64, 'zoneId' => 4, 'rate' => 39.40, 'start' => now(), 'end' => now()],
            ['employeeId' => 64, 'zoneId' => 5, 'rate' => 39.63, 'start' => now(), 'end' => now()],
            ['employeeId' => 64, 'zoneId' => 6, 'rate' => 40.04, 'start' => now(), 'end' => now()],
            ['employeeId' => 64, 'zoneId' => 7, 'rate' => 40.38, 'start' => now(), 'end' => now()],
            // Mustafa Uysal
            ['employeeId' => 65, 'zoneId' => 1, 'rate' => 37.65, 'start' => now(), 'end' => now()],
            ['employeeId' => 65, 'zoneId' => 2, 'rate' => 37.82, 'start' => now(), 'end' => now()],
            ['employeeId' => 65, 'zoneId' => 3, 'rate' => 38.10, 'start' => now(), 'end' => now()],
            ['employeeId' => 65, 'zoneId' => 4, 'rate' => 38.28, 'start' => now(), 'end' => now()],
            ['employeeId' => 65, 'zoneId' => 5, 'rate' => 38.51, 'start' => now(), 'end' => now()],
            ['employeeId' => 65, 'zoneId' => 6, 'rate' => 38.92, 'start' => now(), 'end' => now()],
            ['employeeId' => 65, 'zoneId' => 7, 'rate' => 39.26, 'start' => now(), 'end' => now()],
            // Aytekin Zengin
            ['employeeId' => 66, 'zoneId' => 1, 'rate' => 33.21, 'start' => now(), 'end' => now()],
            ['employeeId' => 66, 'zoneId' => 2, 'rate' => 33.38, 'start' => now(), 'end' => now()],
            ['employeeId' => 66, 'zoneId' => 3, 'rate' => 33.67, 'start' => now(), 'end' => now()],
            ['employeeId' => 66, 'zoneId' => 4, 'rate' => 33.84, 'start' => now(), 'end' => now()],
            ['employeeId' => 66, 'zoneId' => 5, 'rate' => 34.07, 'start' => now(), 'end' => now()],
            ['employeeId' => 66, 'zoneId' => 6, 'rate' => 34.48, 'start' => now(), 'end' => now()],
            ['employeeId' => 66, 'zoneId' => 7, 'rate' => 34.83, 'start' => now(), 'end' => now()],
        ]);
    }
}
