version: '3'
services:
    #||-----------------------------------||
    #|| CONTAINER FOR POSTGRES            ||
    #||-----------------------------------||
    postgres:
        container_name: dubocq_postgres
        image: postgres:latest
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
        networks:
            - backend

    #||-----------------------------------||
    #|| CONTAINER FOR PGADMIN             ||
    #||-----------------------------------||
    pgadmin:
        container_name: dubocq_pgadmin
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "5050:80"
        depends_on:
            -   postgres

networks:
    backend:
